# Generated by Django 3.0.6 on 2020-06-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_experience_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='details',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='info',
            name='objective',
            field=models.CharField(max_length=350),
        ),
    ]
