# Generated by Django 3.0.6 on 2020-06-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200602_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('objective', models.CharField(max_length=350)),
                ('image', models.ImageField(upload_to='resume/images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
