# Generated by Django 3.0.6 on 2020-06-02 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
