# Generated by Django 3.0.6 on 2020-06-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Icon',
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
